# Generated by Django 3.2.6 on 2021-11-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('MinCartValue', models.IntegerField()),
                ('ValidFrom', models.DateTimeField()),
                ('ValidTo', models.DateTimeField()),
                ('CouponCount', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentGateway', models.CharField(max_length=50)),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DiscountType', models.CharField(choices=[('F', 'Flat'), ('P', 'Percent')], max_length=1)),
                ('MinCartValue', models.IntegerField()),
                ('MaxCartValue', models.IntegerField(null=True)),
                ('DiscountValue', models.IntegerField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coupon')),
            ],
        ),
    ]
